### ISSUE TITLE
SPサーバーからCookie（JWT）を受け取る

### ISSUE THREAD

**Issue by yoshinobu-etou-id** [npocccties/chiloportfolio#9]
SPサーバーからCookieにてeppnとnameをJWT化して受け取る想定。
ウォレット側が実装できたらその処理を流用予定。

**Comment by ties-makimura** [comment]
今回，属性はnameではなく正確には表示名（jaDisplayName or displayName）を利用します．（姓や名は渡さない）
認識ずれないよう念のためコメントしておきます．
https://meatwiki.nii.ac.jp/confluence/pages/viewpage.action?pageId=12158166
